# Compute mean and standard deviation of IP102 dataset

Along the 3 channels, for transfer learning from the pretrained Resnet50 network by Wu et al.

In [1]:
import torch
import torchvision
import numpy as np
import sys
from torchvision import datasets, transforms

In [2]:
data_transforms = transforms.Compose([
    transforms.Resize([224, 224]),
    transforms.ToTensor()
])

image_directory = "/Users/eva/Projects/3A_DeepLearning/ip102_v1.1"

dataset_full = datasets.ImageFolder(image_directory, data_transforms)
print(len(dataset_full), 'images')

loader = torch.utils.data.DataLoader(dataset_full, batch_size=16, shuffle=False, num_workers=1)

In [14]:
# Compute mean and stdev along the 3 channels

mean = 0.
std = 0.
nb_samples = 0.

for data, target in loader:
    #print(type(data))
    #print(len(data))
    #print(type(data[0]), type(data[1]))
    #print(data[0].size(), data[1].size())
    batch_samples = data.size(0)
    data = data.view(batch_samples, data.size(1), -1)
    mean += data.mean(2).sum(0)
    std += data.std(2).sum(0)
    nb_samples += batch_samples

mean /= nb_samples
std /= nb_samples

In [15]:
print(mean)
print(std)
print(std**2)

tensor([0.5139, 0.5406, 0.3881])
tensor([0.1889, 0.1877, 0.1880])
tensor([0.0357, 0.0352, 0.0354])
